### ISSUE TITLE
Support for ITC1600 in HekaIOBridge.cpp

### ISSUE THREAD

**Issue by ragavsathish** [Symphony-DAS/symphony-core2#2]
Below function uses max(USB18_NUMBEROFOUTPUTS,ITC18_NUMBEROFOUTPUTS) to define the output and input channels but ITC 1600 uses 32, 15 as Input, output channels 

```
void IOBridge::WriteOutput(IDictionary<ChannelIdentifier, array<itcsample_t>^>^ output, bool preload)
	{
		if(output->Count == 0) {
			return;
		}

	ITCChannelDataEx outputData[max(USB18_NUMBEROFOUTPUTS,ITC18_NUMBEROFOUTPUTS)];
	...

IDictionary<ChannelIdentifier, array<itcsample_t>^>^ 
		IOBridge::ReadWrite(IDictionary<ChannelIdentifier, array<itcsample_t>^>^ output,
		IList<ChannelIdentifier>^ input,
		int32_t nsamples,
		CancellationToken^ token)
	{
	...
```	

As of now I have hard coded IO channels for ITC1600 and ended up in maintaining separate binaries.
Could you advice on how to refactor it ?

**Comment by cafarm** [comment]
Replace with ITC00_NUMBEROFOUTPUTS and ITC00_NUMBEROFINPUTS. Something like ITC_MAX_NUMBER_OF_OUTPUTS and ITC_MAX_NUMBER_OF_INPUTS would be more appropriate but those constants don't exist.

84185629609bf2a544651b9f5140a666f1549d2d
